name: Shuttle Deploy

on:
  push:
    branches: [ "global-ms" ]
  workflow_dispatch:



jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          name: "global-chat-ms-v1"
          allow-dirty: "true"
          no-test: "true"
          cargo-shuttle-version: "0.28.1"
          secrets: |
            REDIS_URI = ${{ secrets.REDIS_URI }}
